apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: elastic-app
  name: elastic-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: elastic-app
  template: 
    metadata: 
      labels: 
        app: elastic-app
    spec: 
      containers: 
        - name: toolbox
          image: sravangcpdocker/login:latest
          imagePullPolicy: Always
          ports: 
            - containerPort: 8080
          env:
            - name: SECRETS_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-user-credentials
                  key: username
            - name: SECRETS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-user-credentials
                  key: password
            - name: CONNECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysqldb
                  key: connection-name  
            - name: PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: mysqldb
                  key: project-id                             
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command: ["/cloud_sql_proxy", "-instances=proxy_name=tcp:3306", "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: secrets-volume
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: secrets-volume
          secret:
            secretName: cloudsql-proxy-credentials
